### ISSUE TITLE
Estimate versus Test Statistic?

### ISSUE THREAD

**Issue by jwbowers** [acoppock/ri2#21]
Right now `summary(riobject)` returns something like 

```
  term estimate two_tailed_p_value
1    Z     0.21                  0
```

Given the flexibility of ri2, since this is the value of the observed test statistic and is not necessarily a good estimate of any particular target, wouldn't it be better to label this as something like "observed test statistic"?

**Comment by acoppock** [comment]
I do see your point. in some cases the test stat is the same number as an estimate (as in ate-hat) but other times there no real sense in which it's an estimate of a model parameter, like an f-stat or something.  

The main reason to call it "estimate" is to maintain consistency with the broom package -- that way when you call `tidy(riobject)` you get a column name that matches the broom workflow. 

Not sure how to balance these considerations....

**Comment by jwbowers** [comment]
Good point. Not a big deal. Just mostly an FYI.
