### ISSUE TITLE
Pipeline for Balancing table

### ISSUE THREAD

**Issue by lucasmation** [acoppock/ri2#22]
@acoppock , nice package, tks!

Do have any simple pipeline to produce a Balancing table based on conduct_ri for a (potentially long) set of covariates?

**Comment by acoppock** [comment]
I would tend to recommend a joint test (like the omnibus ri f-test in the examples, see `?conduct_ra`) over a one-by-one balance table, since all those tests are correlated with each other.  But that's not exactly your question!  

how about something like this:

```
library(tidyverse)
library(ri2)
N <- 10
declaration <- declare_ra(N = N, m = 5)

dat <- tibble(X1 = rnorm(N),
              X2 = rnorm(N),
              X3 = rnorm(N),
              Z = conduct_ra(declaration))

covs <- c("X1", "X2", "X3")

balance <- 
  covs %>%
  map( ~ paste0(., " ~ Z")) %>%
  map( ~ conduct_ri(
    formula = .,
    assignment = "Z",
    declaration = declaration,
    data = dat
  )) %>%
  map_df(tidy) %>%
  mutate(covariate = covs)

balance
```
